### ISSUE TITLE
Would you consider using modern CMake?

### ISSUE THREAD

**Issue by ooxi** [mbedded-ninja/MFixedPoint#94]
Would you consider using modern CMake practices like `target_compile_definitions` instead of `add_definitions`? This would imply raising the minimum required CMake version though.

I would be happy to provide a patch, if you are interested.

**Comment by gbmhunter** [comment]
Yes I am totally for modernizing the CMake!

A patch would be appreciated. If it works, I might consider updating all my other CMake driven repos to use similar syntax.

Regards, Geoff

**Comment by ooxi** [comment]
That's lovely! I'll prepare a patch and come back to you :-)
